// GameConstants.cs
//
// Author:
//       Fortyseven <fortyseven@gmail.com>
//
// Copyright (c) 2014 2014
//
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Game
{
    public class GameConstants
    {
        public static float SCREEN_X_BOUNDS = 12.0f;
        public static float SCREEN_Y_GEN_OFFSET = 17.0f;
        public static float SCREEN_Y_FLOOR = 0.0f;
        public static int SCORE_ASTEROID_LG = 10;
        public static int SCORE_ASTEROID_SM = 20;
        public static int SCORE_BOMB_LG = 40;
        public static int SCORE_BOMB_SM = 80;
        public static int SCORE_KILLSAT = 50;
        public static int SCORE_UFO = 100;
    }
}

